### PR TITLE
Replace eval with a proper importer.

### PR DESCRIPTION
**Pull request by paultag**
Basically, there's a bug with which set of globals gets passed into the
 definitions files, which can result in some globals going missing(!)
 even though they're in the source file (and work if you run it by hand)

 This uses the correct PEP 302 import code for Python 3, and uses the
 Python 2 `imp` module as a compat shim.

 This was discovered by @mileswwatkins after trying to use `csv` inside
 a namer function. Thanks, Miles!

### CODE REVIEW

**Comment by jpmckinney** [comment]
Looks good!

Btw, is checking `sys_version` more "idiomatic" that rescuing an `ImportError`?

**Comment by paultag** [comment]
@jpmckinney - yeah, I usually to a `try` / `except` if there's a good chance the module won't be there (e.g. `simplejson` vs `json` in ye olde era), but in places where I should know which to pick, I tend to dispatch based on that, so that errors never get hidden (no matter how unlikely it is a builtin goes missing :) )

Happy to adopt whatever style is most idiomatic :)

**Comment by paultag** [comment]
Tests are failing for a reason I'm not sure about, does master work on those configs?

**Comment by jpmckinney** [comment]
Master is passing.

**Comment by paultag** [comment]
Hunh. OK, I'll look into that.

On Fri, Apr 24, 2015 at 3:33 PM, James McKinney <notifications@github.com>
wrote:

> Master is passing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opennorth/represent-boundaries/pull/30#issuecomment-96042903>
> .
>



-- 
:wq

**Comment by jpmckinney** [comment]
Can I see the code to reproduce the bug this is supposed to fix?

The failure has to do with the definition files not living in a hierarchy of Python modules.

**Comment by paultag** [comment]
@jpmckinney - I don't have the diff handy, but basically, if you do something like:

```python
import csv

def something_namer():
    csv.DictReader(...)
    ....
```

It'll rase a `NameError: name 'csv' is not defined` - and after knowing what's going on here, you *should* be able to do something like `print(__file__)`, you'd see this bug right out -- the `locals`/`globals` will be from the **calling** function, e.g. `__file__` will say `boundaries/__init__.py`.

Basically, using `eval` for this really breaks things. I'll revise the generated module name approach (or pop it out of sys modules after loading?)

**Comment by jpmckinney** [comment]
I think you just need to put the import inside the def and it works.

**Comment by mileswwatkins** [comment]
That's the solution that I've been using locally in the meantime, and I can confirm that it works. But it definitely feels kludgey.

**Comment by jpmckinney** [comment]
`definition.py` files are just config files, and it's convenient to have them lie around in pretty much any directory they like, without having to worry about `__init__.py` files all over your directory tree. If there's a solution that doesn't create a bunch of warnings, such a solution can be merged. If the choice is between ugly warnings when doing things normally and having to put imports inside helper functions, I prefer imports inside helper functions.

**Comment by paultag** [comment]
@jpmckinney just because we can workaround doesn't mean the existing behavior isn't correct :)

I can fix it to work, if you look, most of the tests pass, I don't think we need to throw out the approach due to it failing under odd cases. It'll be easy to not do `__init__.py` all over the place.

**Comment by jpmckinney** [comment]
Is there a way to get the remaining tests to pass? They are failing because more warnings are being created than expected.

**Comment by paultag** [comment]
Sure, why not?

**Comment by jpmckinney** [comment]
Ok, cool, I'll wait for the commit :)

**Comment by paultag** [comment]
Coveralls is a bit more unhappy, but that's just because we have a 2/3 dispatch :)

I'm sure the coverage remains the same if you calculate coverage over both 2 and 3 codepaths.

Also, I think they should all be green now, @jpmckinney

**Comment by paultag** [comment]
Added a big-ass comment explaining why

**Comment by jpmckinney** [comment]
Thanks!

**Comment by paultag** [comment]
Thank you, @jpmckinney !

**Comment by jpmckinney** [comment]
0.6.6 released https://github.com/opennorth/represent-boundaries/blob/master/CHANGELOG.md#066-2015-04-24

**Comment by paultag** [comment]
You're the best, thank you!

On Fri, Apr 24, 2015 at 5:44 PM, James McKinney <notifications@github.com>
wrote:

> 0.6.6 released
> https://github.com/opennorth/represent-boundaries/blob/master/CHANGELOG.md#066-2015-04-24
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opennorth/represent-boundaries/pull/30#issuecomment-96074237>
> .
>



-- 
:wq

**Comment by jpmckinney** [comment]
Actually, make that 0.7.0. There was a edge-case backwards incompatibility (if you were relying on the globals from `boundaries/__init__.py` being available, like `re`).

**Comment by paultag** [comment]
Hah, ah. Awww.

Wellp. Perhaps that breaking is for the best :)

On Fri, Apr 24, 2015 at 6:01 PM, James McKinney <notifications@github.com>
wrote:

> Actually, make that 0.7.0. There was a edge-case backwards incompatibility
> (if you were relying on the globals from boundaries/__init__.py being
> available, like re).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opennorth/represent-boundaries/pull/30#issuecomment-96079097>
> .
>



-- 
:wq

**Pull request merged**
