### PR TITLE
Switch to Django 1.9 JSONField

### PR DESCRIPTION
**Pull request by rhymeswithcycle**
Despite my earlier comments about switching to the Django `JSONField` being unnecessary, I later saw that the version of the `jsonfield` dependency in use had the weird behaviour of using a `json` column type if the database was initially created on Postgres >= 9.2, and a `text` column type otherwise (and not altering the column type if you later upgrade Postgres).

This should migrate to a `jsonb` column type for all. I tested the migrations locally on Postgres 9.5, starting from both `json` and `text` column types and encountered no problems. After migrating to `jsonb`, I did a cursory test of the API (a boundary resource displays correctly) and of `loadshapefiles`.

### CODE REVIEW

**Comment by rhymeswithcycle** [comment]
(working on test failures now)

**Comment by rhymeswithcycle** [comment]
(almost done fixing this, but have some appointments now, so will return to this later today)

**Comment by rhymeswithcycle** [comment]
Tests passing now -- apologies for the commit spam, was debugging things with Travis and, well, that's how it goes.

**Comment by jpmckinney** [comment]
Thanks!

**Pull request merged**
